src/content/blog/arm64-apple-silicon-m1-ddev-local-what-does-it-all-mean.md

I'm writing a new article on ARM64 migration for different reasons, but wanted to drop in and update this one.

Update article on ARM64

---

src/content/blog/controlling-cms-settings-files-in-ddev-local.md
src/content/blog/customizing-ddev-local-images-with-a-custom-dockerfile.md
src/content/blog/ddev-docker-chromebook.md
src/content/blog/ddev-local-and-phpstorm-debugging-with-wsl2.md
src/content/blog/ddev-local-automated-testing.md
src/content/blog/ddev-local-database-management.md
src/content/blog/ddev-local-for-laravel-teams.md
src/content/blog/ddev-local-phpstorm-and-xdebug-debugging.md
src/content/blog/ddev-local-scratch-macos.md
src/content/blog/ddev-local-trusted-https-certificates.md
src/content/blog/eight-more-ways-to-get-the-most-out-of-ddev-local.md
src/content/blog/getting-started-with-ddev-and-composer.md
src/content/blog/moving-cms-sites-around-local-servers.md
src/content/blog/oh-my-zsh-using-custom-commands-and-other-goodies-to-add-to-ddev.md
src/content/blog/open-source-collaboration-signing-tools-for-macos-catalina.md
src/content/blog/save-as-you-go-and-make-backups-in-a-jiffy-with-ddev-local.md
src/content/blog/sharing-a-ddev-local-project-with-other-collaborators.md
src/content/blog/ten-more-ways-to-increase-your-efficiency-with-ddev-local.md
src/content/blog/using-ddev-to-teach-open-source-web-development.md
src/content/blog/watch-ddev-local-from-scratch-with-macos.md
src/content/blog/watch-ddev-local-from-scratch-with-windows-wsl2.md
src/content/blog/watch-ddev-local-new-casual-webhosting-feature.md
src/content/blog/watch-ddev-local-on-arm64-raspberry-pi.md
src/content/blog/why-use-ddev-local-instead-of-rolling-your-own-docker-based-local-dev-solution.md

Mostly
* DDEV-Local -> DDEV
* Remove DDEV-Live references
But I did get carried away in some other edits.

Move DDEV-Local -> DDEV and remove DDEV-Live

---

README.md

README: Add link to Cloudflare setting for GITHUB_TOKEN

---

src/components/quickstart/Cloud.astro

Same as https://github.com/ddev/ddev/pull/5060

gh codespaces install docs: update docker-in-docker to v2

---

src/content/blog/contributor-training.md

Adds blog with form about contributor training.

Add blog about contributor training

---

src/content/blog/contributor-training.md

Fix blog link URL

---

src/content/blog/contributor-training.md

This fixes an incorrect date and capitalizes “Zoom”. Merge away if you approve!

Fix typos.

---

src/content/blog/contributor-training.md

Add link to today's training, remove it from previous upcoming list.

Add link to docs training

---

src/content/blog/contributor-training.md

Add two new trainings, test infra and tests training

Add test infrastructure and tests training to contributor training page

---

src/content/blog/contributor-training.md

* Add amplitude training
* I have more to go, will keep adding to this.

Add amplitude training to contributor training

---

src/content/blog/contributor-training.md

Update with this week's recording.

Add new support training to contributor-training

---

src/content/blog/how-to-give-and-get-community-support.md

I created a blog post for the contributor training on Tuesday (8/22/23)
I ran textlint... It didn't like the phrase "not just answers", and I sort of struggled to come up with a suitable replacement for the word "just". 
@mattstein if you have any suggestions to improve my writing in this post, please let me know because I appreciate your input. @rfay - All of the original content from your outline is there, but I reorganized it and tried to elaborate on some points by including some of your spoken content too. Please let me know if I missed something important?

Add blog post for August 22, 2023 contributor training

---

src/content/blog/contributor-training.md
src/content/blog/unleashing-php-development-with-ddev.md

* Update a couple of things in contributor-training
* Stronger title for Lasse's guest blog

blog: update contributor-training with new video

---

src/content/blog/contributor-training.md

Move marketing to done

---

src/content/blog/contributor-training.md

Add recording for 2023-09-19 Testing Infrastructure

Add recording for 2023-09-19 Testing Infrastructure

---

src/pages/foundation.astro

The foundation page showed future tense for 501(c)(3) application, but it's been done.

update foundation page to show 501c3 already applied for

---

src/content/blog/contributor-training.md

Update contributor-training with current status

Update with automated tests in past

---

src/content/blog/expanding-ddev-maintainer-team.md

@deviantintegral had some comments about the "how we'll fund maintainers" blog post, updates here.

blog: update info about Stas etc

---

.github/CODEOWNERS

Add @rfay and @bmartinez287 to CODEOWNERS

Update codeowners, add bmartinez287

---

src/pages/index.astro

Based on our discussion on #77.
This updates the homepage to link to more relevant information.

Update repository list

---

src/content/blog/contributor-training.md

Amplitude training session yesterday added to contributor training blog.

add amplitude session to contributor training blog

---

src/pages/support-ddev.astro

This PR adds links to each support pattern on the contributing page.
- highlights at glance some methods
- enables links that can be shared

Highlight support patterns

---

src/components/Footer.astro
src/pages/support-ddev.astro

This PR improves the visibility of the training sessions by:
- adding link in footer to blog post.
- adding a section on the contributing page.

Promote training sessions

---

src/content/blog/contributor-training.md

Add contributor training video for hosting providers.

Update video for provider training

---

src/content/blog/2023-review.md

@bmartinez287 pointed out the importance of contributor training in 2023.

2023 review: Add more about contributor training

---

src/components/Footer.astro
src/components/Header.astro
src/const.ts

Adds the DDEV store links to ddev.com

Add DDEV store links.

---

.github/workflows/test.yml

The build might fail crashing the site.
Add npm run build to the ci test.

Add npm run build to the ci test.

---

README.md

* Fix title on README
* Experiment with forked PR and tests

Fix title on README - experiment with forked pr

---

src/content/blog/501c3.md

fix broken link in 501c3 blog

---

src/content/blog/ddev-and-xz-backdoor.md

@rpkoller suggestions for xz article

@rpkoller suggestions for xz article

---

src/content/blog/working-with-vite-in-ddev.md

Add awesome article https://www.lullabot.com/articles/nodejs-development-ddev to the list of examples mentioned in https://ddev.com/blog/working-with-vite-in-ddev/

Add NodeJS tutorial by Andy Blum to Vite article

---

src/content/blog/2024-plans.md

Add a bit of nuance about platform.sh/upsun goals for 2024.

Update details about platformsh/upsun plans in 2024 plans

---

src/content/blog/contributor-training.md

It's time to restart contributor training. 
Prepare a list and schedule!

Prepare a new set of contributor trainings

---

src/components/AnimatedTerminal.astro

The terminal output is for the old DDEV version.
Updates it.

Update animated terminal

---

src/content/blog/working-with-vite-in-ddev.md

Most important info is buried in the article
Add top section with common config

docs: update working with vite to add important info on top

---

src/content/blog/working-with-vite-in-ddev.md

Gitpod had no example yet, Codespaces was a bit too detailed (and I updated my repos)
Add Gitpod, shorten Codespaces

docs: update gitpod and codespaces for working with vite

---

.github/workflows/test.yml

- #195
My workaround is no longer needed as the fix has been merged upstream.
Checking if the tests work without it.

test: remove workaround for withastro/action, for #195

---

src/pages/about.astro

Grammar typo "... and the and was visionary ..."
Removes "and the"
--
--
--
--

Fix grammar typo in about.astro

---

README.md
src/content/blog/contributor-training.md
src/content/blog/ddev-docker-architecture.md
src/content/blog/golang-debugging.md
src/content/blog/how-to-give-and-get-community-support.md
src/content/blog/open-source-collaboration-signing-tools-for-macos-catalina.md
src/content/blog/setting-up-a-go-development-environment.md
src/content/blog/xdebug-debugging.md
src/content/config.ts

It makes sense to have "training" category for contributor training
* Add category
* Tag blogs with it

Add training category and tag blogs

---

src/components/quickstart/Cloud.astro

- https://github.com/ddev/ddev/issues/6399
Changes `https://codespaces.new` to `https://github.com/codespaces/new`

Update Codespaces link

---

src/featured-sponsors.json

- #212
Removes small logo.
Open https://20240714-stasadev-remove-dup.ddev-com-front-end.pages.dev/
And scroll down to featured sponsors.

Remove duplicate logo, for #212

---

src/content/blog/advanced-add-on-contributor-training.md
src/content/blog/contributor-training.md

I hadn't been keeping up the master contributor training page.

Update links in contributor training

---

tailwind.config.cjs

I have a hard time telling if I'm looking at the code or something else.
Use style similar to GitHub.
Example from https://ddev.com/blog/anatomy-advanced-ddev-addon/
Before:
After:
Before:
After:

GitHub style for inline code blocks

---

src/content/blog/working-with-vite-in-ddev.md

- add toc for better anchor linking to headings
- add ddev vite addon by @s2b
- general optimizations of the article

Add vite sidecar addon and toc

---

src/content/blog/working-with-vite-in-ddev.md

- https://github.com/ddev/ddev.com/pull/237

docs: add advanced usage info regarding autostart of Vite

---

package-lock.json

Some packages are outdated and have newer releases.
Preview URL.
`https://d22f7090.ddev-com-front-end.pages.dev/`

Updates npm packages.

---

README.md
public/_redirects

* Add `port-conflict` redirect
* Add redirect technique to README

Add port-conflict redirect for short link in ddev

---

README.md
public/_redirects

@stasadev pointed out I should use /s prefix and 301 redirect. Done here, updated README

Change to use short link and 301

---

src/components/FeaturedSponsors.astro
src/featured-sponsors.json
src/pages/resources/featured-sponsors-darkmode.svg.js
src/pages/resources/featured-sponsors.svg.js

* #44 
Platform.sh and future "lead sponsors" want a more prominent listing.
Review at https://20241108-add-leading-sponsor.ddev-com-front-end.pages.dev/#supporters
Review the main page in regular and dark mode.

Add "leading sponsor" setup to sponsors display, fixes #44

---

src/content/blog/windows-ddev-setup.md

Sometimes I find more things I need to do on Windows setup.

windows: add more packages to install

---

src/featured-sponsors.json

Fame Helsinki just restarted their contribution :)

Re-add FameHelsinki, who just restarted their contribution

---

public/_redirects

- #306
Found one more old link from `master`.
Replace it with `main`.

refactor: update redirect link

---

astro.config.mjs
package-lock.json
package.json
postcss.config.cjs
src/components/AnimatedTerminal.astro
src/components/Header.astro
src/components/PlatformPicker.astro
src/components/Tabs.astro
src/components/Terminal.astro
src/styles/global.css

Tailwindcss had a major release recently. This PR updates our codebase to take advantage of it while maintaining backward compatibility for certain features on v3 until they have compatible options.

Updates tailwindcss to v4 and other config as needed.

---

public/_redirects

Preparing presentation for Florida Drupalcamp, need link to that URL

Add redirect for divide-and-conquer presentation

---

README.md

- https://github.com/ddev/ddev.com/pull/347#issuecomment-2786465197
Adds information about how I converted PNG to SVG.

docs: add info about PNG to SVG conversion

---

src/content/blog/building-offramp-from-wordpress-with-ddev.md

Fix run-on typo in offramp blog

---

src/content/blog/ddev-expose-node-app-on-subdomain.md

Typo in title, _HHTPS_.
Fixes typo with _HTTPS_.

Fix typo in article title

---

src/scripts/sponsors-banner.js

For:
- #363
I refactored the banner using ChatGPT.
Review https://20250502-stasadev-sponsors-j.ddev-com-front-end.pages.dev/

refactor: improve sponsors banner layout, for #363

---

src/content/blog/ddev-may-2025-newsletter.md

May 2025 newsletter
Rendered at https://20250505-may-2025-newsletter.ddev-com-front-end.pages.dev/blog/ddev-may-2025-newsletter/

May 2025 newsletter

---

src/content/blog/working-with-vite-in-ddev.md

Add viget article & iamntz/wp-vite-manifest to documentation

---

README.md
src/components/PostBody.astro
src/scripts/giscus-comments.js

feat: add giscus comments, fixes #309

---

.gitignore
CLAUDE.md
src/content/blog/ddev-docker-chromebook.md
src/content/blog/windows-ddev-setup.md

We're experimenting with claude code.
This adds a CLAUDE.md with basic instructions.

Add a CLAUDE.md for basic claude instructions

---

src/pages/foundation.astro

@stasadev noted that there was incorrect information about Randy not receiving funds
Thanks!
Review updated foundation.astro at https://20250712-rfay-foundation.ddev-com-front-end.pages.dev/foundation/

Update foundation.astro with current info

---

src/content/blog/ddev-add-on-maintenance-guide.md

- https://github.com/ddev/ddev-addon-template/pull/76
Adds it.
https://20250722-stasadev-addon.ddev-com-front-end.pages.dev/blog/ddev-add-on-maintenance-guide/

blog: add update checker script
