src/components/quickstart/Cloud.astro, src/components/quickstart/Linux.astro
* pkg.ddev.com is the new CNAME for packages; update it.
* Report of a typo in https://discord.com/channels/664580571770388500/1087760493986467871/1094750674031497256 - apparently happened during drud/ddev changeover.
This is related to the same set of changes for the docs:
* https://github.com/ddev/ddev/pull/4808
=> Update DDEV install instructions for pkg.ddev.com

src/components/Badge.astro, src/components/Hero.astro
Mayank pointed out [in Discord](https://discord.com/channels/664580571770388500/1096577998712487936/1096577998712487936) that one of DDEV’s strengths is its platform support, which includes macOS M1 and M2 architecture. We don’t point that out anywhere on the homepage despite it being important!
This adds a prominent architecture callout to the homepage, using “Intel” and “Apple” next to “macOS” to specifically identify those platforms. (This seemed like it’d be more maintainable than listing out M1, M2, and continuing to tack on M* labels as new chips are released.)
[Visit the preview build](https://feature-homepage-architectur.ddev-com-front-end.pages.dev) and see what you think! My goal was to keep it from being too loud, but reinforce the supported architectures in a way that’s as …
=> Add homepage architecture callout

src/components/AnimatedTerminal.astro, src/components/quickstart/Mac.astro, src/components/quickstart/Windows.astro
Some minor things getting out of date.
Reviewing this as a result of reading the [Nix docs](https://nix.dev/tutorials/#tutorials), which have tutorials to start with, like you have here. I'd sure like to figure out how to incorporate the amazing work you've done here directly into the docs. Or docs directly into ddev.com (better). 
It's so important for people to have an easy startup experience, and right now the docs are scattered, as hard as they try. ddev.com is much better.
=> Minor time-has-passed updates to tutorials

src/content/blog/contributor-training.md, src/content/blog/ddev-website-for-contributors.md
* Add image that was intended to land earlier but wasn't referenced in https://github.com/ddev/ddev.com-front-end/pull/83
* Add credit for @kristin-wiseman in that one
* Update modified date on contributor training
I hope this is OK @kristin-wiseman
=> Add image for ddev.com training

src/components/AnimatedTerminal.astro
I didn’t realize it, but [this commit](https://github.com/ddev/ddev.com/commit/c3fbd9f1ca6c2d355f9020f36854f45b039c1edc) added lines to the animated `ddev describe` screen, and the bottom of the CLI table is clipped.
This adjusts the animation settings to account for the extra line.
=> Fix `ddev describe` animation clipping

src/pages/blog/index.astro, src/pages/index.astro
If a person plops `https://ddev.com` or `https://ddev.com/blog/` into Feedly, no feeds are listed even though the alternate RSS and JSON feeds are present in `link` tags for blog listing and detail pages.
This is, of course, a bummer.
This adds those `link` tags to the homepage—which doesn‘t affect it visually—and further specifies a MIME type in each tag’s `type` property. For whatever reason, this makes Feedly happy and it lists “DDEV Blog” twice (once per feed, presumably) if you supply either URL above.
Swing by your Feedly account and add `ddev.com` to the search bar under **Follow your favorite websites**. Joyfully confirm that you’re able to select “DDEV Blog”.
n/a
n/a
n/a
=> Help Feedly find feed links

src/styles/global.css
The icons on the footer match the ones on the brand bar.
=> Fix footer contrast on darkmode

src/components/Hero.astro
Closes #103 
It adds smaller margins and paddings on mobile devices.
=> Add mobile first spacing to hero header.

src/components/Heading.astro, src/const.ts, src/pages/blog/[slug].astro
The docs have a quick edit button that directs one straight to the docs but the blog does not.
This PR tries to address that.
I used the example the Astro docs had and placed it on what seemed to be the most convenient place.
=> Add a blog edit link

src/pages/search.astro
The issue is described here
* https://github.com/ddev/ddev.com/issues/146
It adds the domain to the javascript search utility.
=> Fixes DDEV search component.

src/styles/global.css
https://ddev.com/blog/drupal7-drupal9-migration-ddev-acquia-migrate-accelerate/
With dark mode, the text highlighted in yellow becomes too hard to read.
This switches it to HTML blue.
=> Fixes dark mode contrast issue with html mark.

src/content/blog/2023-review.md
I don't know how I missed these in review 😅.
Removes redirects.
https://20240228-stasadev-fix-links.ddev-com-front-end.pages.dev/blog/2023-review/
=> Fix links in DDEV 2023 Review article

.textlintrc
While well-intentioned, the ban on the word "just" causes unjust and unnecessary reformulations of sentences. It's doing more harm than good. I'll try not to use the word in a demeaning way.
=> Allow the word just

src/content/blog/ddev-name-resolution-wildcards.md
I think this is a better test as it won't likely be in a `hosts` file and covers the situation where first level wildcards work and deeper fails. It also answers the question directly and provides a next step.
=> Improve ddev-name-resolution-wildcards.md with reference to debugging

src/components/quickstart/Mac.astro
Our default/easiest recommendation these days is Orbstack, not Docker Desktop
Switch to the new recommendation
Review at https://20240328-use-orbstack.ddev-com-front-end.pages.dev/get-started/ - macOS version
=> switch default to Orbstack for get started

src/content/blog/save-as-you-go-and-make-backups-in-a-jiffy-with-ddev-local.md
I noticed a couple of things that still needed help in the article on snapshots and exports.
=> Minor fixes to save-as-you-go

.github/workflows/test.yml
Tests are broken:
```
Warning: No existing directories found containing cache-dependency-path="./yarn.lock"
```
I investigated this and found that it is a problem in `withastro/action@v2`
I opened a PR there, but don't know if it is going to be merged soon:
- https://github.com/withastro/action/pull/52
1. Removes all `yarn.lock` files from `node_modules` directory before running `withastro/action@v2`. (This workaround can be removed later.)
2. Bumps `actions/checkout` and `actions/setup-node` to `v4`.
3. I found out that `withastro/action@v2` uses `node-version`, but we do not set it explicitly - fixed.
=> fix: make tests work again, bump GitHub dependencies

src/components/quickstart/Cloud.astro, src/components/quickstart/Linux.astro
- https://github.com/ddev/ddev/issues/5915
Adds `curl` installation for Debian/Ubuntu.
Updates the link for GitHub Codespaces.
=> docs: install curl, update codespaces link

src/components/Hero.astro
The macOS badge on the main page mentions M1, M2, but M3 is already there and M4 is almost out.
Use `M Series` as the generic name, I got it from https://en.wikipedia.org/wiki/Apple_silicon
=> Use `M Series` as a badge for macOS

src/content/blog/working-with-vite-in-ddev.md
The Laravel Vite plugin (https://www.npmjs.com/package/laravel-vite-plugin) now accepts the standard vite config used for other CMSes.
Remove the old workaround solution with hmr host
none
none
- https://github.com/ddev/ddev/pull/6220
=> Update Vite tutorial section for Laravel

src/content/blog/ddev-docker-architecture.md, src/content/blog/golang-debugging.md, src/content/blog/one-minute-wordpress.md, src/content/blog/randy-in-patagonia.md, src/content/blog/traefik-configuration-contributor-training.md, src/content/blog/xdebug-debugging.md
Some iframe video links look bad on mobile https://ddev.com/blog/xdebug-debugging/
Wraps them into `<div class="video-container"></div>`
Open on mobile (or change the view to mobile using the browser's developer console)
https://20240714-stasadev-wrap-ifram.ddev-com-front-end.pages.dev/blog/xdebug-debugging
=> Wrap iframe video links for mobile

src/pages/search.astro
When you search something here https://ddev.com/search/, it produces a link with double slash
Removes this extra slash.
Try searching here https://20240714-stasadev-search-ext.ddev-com-front-end.pages.dev/search/
=> Remove extra slash in the search URL results

src/content/blog/advanced-add-on-contributor-training.md
- https://github.com/ddev/ddev/pull/6433
- https://github.com/ddev/ddev/issues/5969
- Adds `ddev_version_constraint` example.
- Removes `#ddev-nodisplay`.
See https://20240731-stasadev-ddev-versi.ddev-com-front-end.pages.dev/blog/advanced-add-on-contributor-training/
=> Add `ddev_version_constraint` example, remove `#ddev-nodisplay` for add-ons

src/content/blog/amd64-on-apple-silicon-ddev.md
The blog post on running amd64 on arm is not explicit enough about requiring and enabling rosetta.
Improve it.
=> Update blog on amd64 on arm64

src/content/blog/working-with-vite-in-ddev.md
- @mortona42 provided infos about Drupal https://github.com/mandrasch/my-ddev-lab/issues/2, thx!
- add info to Vite article
https://github.com/mandrasch/my-ddev-lab/issues/2
=> Add updated Drupal info to Vite article

README.md
- Not clear that you need to open https://ddev.com.ddev.site:4321/ in your browser
- add info
- add info for troubleshooting
=> Improve README for new contributors

src/featured-sponsors.json, src/lib/api.ts
We've been showing long-since expired github sponsors and featured sponsors, and that's not fair to the folks that are currently active.
* Remove inactive featured sponsors
* Remove inactive github sponsors
Review the results on the rendered home page
Rendered 
* [main page](https://20241108-remove-not-current.ddev-com-front-end.pages.dev/#supporters)
* [support ddev page](https://20241108-remove-not-current.ddev-com-front-end.pages.dev/support-ddev/#sponsor-development)
It won't show up on https://github.com/ddev/ddev yet of course, but that should be the same.
=> Remove expired sponsors from sponsors list

src/content/blog/windows-ddev-setup.md
The current command generates an error:
```shell
❯ ssh git@github.com git@github.com
Invalid command: git@github.com
You appear to be using ssh to clone a git:// URL.
```
Confirmed issues in the following terminals:
- PowerShell 7.4.6
- Windows Powershell 5.1.22621.4391
- Git bash 2.47.0.windows.2
Update the command.
Now generates the following:
```
❯  ssh git@github.com
Enter passphrase for key '/c/Users/XXXXXX/.ssh/id_ed25519':
Hi XXXXXX! You've successfully authenticated, but GitHub does not provide shell access.
```
=> docs: Fix `ssh` test command

src/content/blog/working-with-vite-in-ddev.md
I recently released the [ddev-vitest](https://github.com/tyler36/ddev-vitest) add-on.
Vitest is a vite-native testing framework, as a alterantive/succssor to Jest. It even re-uses the same vite.config.js file.
Not sure if you want to include this vite-adjacent addon. A percentage of Vite users are also likely to use Vitest, so I include it for "complete-ness"
Please close if you feel it's outside the original scope.
This PR does the following:
- removes trailing spaces
- adds note & link to  [ddev-vitest](https://github.com/tyler36/ddev-vitest)  addon.
=> docs: add note about ddev-vitest

src/content/blog/release-v1.24.0-php8.4.md
=> Edits to v1.24.0 release blog

public/_redirects
@stasadev pointed out that we could have a discord shortlink instead of the obscure link we currently use, https://discord.com/invite/5wjP76mBJD
Use https://ddev.com/s/discord and redirect.
Test at https://20241206-discord-shortlink.ddev-com-front-end.pages.dev/s/discord
Followup would be to update ddev.com, docs, and any other references.
=> Add discord shortlink

src/components/BlogPostFooter.astro, src/pages/blog/rss.xml.js
- #294
Also I noticed that there was no links to previous posts at the bottom of the post:
Astro replaced `slug` with `id` in most places.
See https://20241223-stasadev-rss-astro.ddev-com-front-end.pages.dev/blog/rss.xml
Before
```xml
<title>DDEV December 2024 Newsletter</title>
<link>https://ddev.com/blog/undefined</link>
<guid isPermaLink="true">https://ddev.com/blog/undefined</guid>
<description>DDEV November 2024 Newsletter</description>
<pubDate>Tue, 03 Dec 2024 00:00:00 GMT</pubDate>
```
After
```xml
<title>DDEV December 2024 Newsletter</title>
<link>https://ddev.com/blog/ddev-dec-2024-newsletter</link>
<guid isPermaLink="true">https://ddev.com/blog/ddev-dec-2024-newsletter</guid>
<description>DDEV November 2024 Newsletter</description>
<pubDate>Tue, 03 Dec 2024 00:00:00 …
```
=> Fix more slugs after Astro upgrade, fixes #294

src/components/quickstart/Mac.astro
* #286 
The [Get Started](https://ddev.com/get-started/) guide uses OrbStack, but does not mention that OrbStack is commercial software.
Added a one-sentence note stating OrbStack is not free for professional use in the [Get Started](https://ddev.com/get-started/) page.
https://github.com/ddev/ddev.com/issues/286
=> Add note stating OrbStack is not free for professional use, fixes #286

src/featured-sponsors.json
Unfortunately, more sponsors have stepped back.
Remove FameHelsinki and OSP. 
Related:
* #273 
Review at https://20250103-remove-inactive-spo.ddev-com-front-end.pages.dev/#supporters
=> Remove more expired sponsors from featured sponsors list

public/.well-known/funding-manifest-urls
Adding funding.json per https://floss.fund
Needs .well-known URL to point back to funding.json
Visit https://20250105-add-well-known.ddev-com-front-end.pages.dev/.well-known/funding-manifest-urls
`curl https://20250105-add-well-known.ddev-com-front-end.pages.dev/.well-known/funding-manifest-urls`
=> Add .well-known funding-manifest-urls link for funding.json

src/content/blog/platform-sh-becomes-a-lead-sponsor-of-ddev.md, src/content/blog/platform-sh-ddev-funding-changes.md
Blog announcing change in Platform.sh sponsorship
Rendered at https://20241226-platformsh-changes.ddev-com-front-end.pages.dev/blog/platform-sh-ddev-funding-changes/
I'm pretty sure we once had a "DDEV + Platformsh header image, but it seems it was lost in https://github.com/ddev/ddev.com/commit/23339600a34a842c52eb19584a291971a58852c9
=> Blog announcing change in Platform.sh sponsorship

src/content/blog/database-improvements.md
I noted these links about MySQL 8.4.3 performance and wanted to add them to the database performance/MySQL 8.4 blog.
=> Add links to MySQL performance improvements

src/content/blog/working-with-vite-in-ddev.md
- Vite changed the default cors security behavior to fix https://github.com/vitejs/vite/security/advisories/GHSA-vg6x-rcgg-rjx6, Patched versions: >=6.0.9, >=5.4.12, <6.0.0, >=4.5.6, <5.0.0
- see https://discord.com/channels/664580571770388500/1334261207049310230
- add fix by @tyler36 
```
export default defineConfig({
// ...
server: {
// ...
cors: { origin: process.env.DDEV_PRIMARY_URL },
```
- https://github.com/vitejs/vite/security/advisories/GHSA-vg6x-rcgg-rjx6
=> docs: add server.cors option for Vite (security)

src/components/Hero.astro, src/components/quickstart/Cloud.astro, src/content/blog/docker-desktop-alternatives-arrive-for-ddev-colima.md, src/content/blog/golang-debugging.md, src/content/blog/maintaining-ddev-tests-contributor-training.md, src/content/blog/tmate-github-actions-contributor-training.md, src/content/blog/whats-so-different-about-ddev-local.md, src/content/blog/working-with-vite-in-ddev.md
Followup task from
* https://github.com/ddev/ddev/pull/6974
Gitpod classic is no longer a thing. We've removed it from the docs, although it hasn't been removed from code.
Review:
* get-started page: https://20250225-remove-gitpod.ddev-com-front-end.pages.dev/get-started/
* Docker Desktop alternatives: https://20250225-remove-gitpod.ddev-com-front-end.pages.dev/blog/docker-desktop-alternatives-arrive-for-ddev-colima/
* What's so different about DDEV: https://20250225-remove-gitpod.ddev-com-front-end.pages.dev/blog/whats-so-different-about-ddev-local/
* https://20250225-remove-gitpod.ddev-com-front-end.pages.dev/blog/working-with-vite-in-ddev/
@mandrasch since I touched your vite article would appreciate you looking.
=> Remove gitpod support suggestions

src/content/blog/2025-plans.md, src/content/blog/database-improvements.md
* Fix typo (launch vs share) in 2025 plans
* Update Database improvements blog with minor corrections and update
=> Minor fixups to 2025 plans and database improvements

src/content/blog/amd64-with-rosetta-on-macos.md
The new blog on running AMD64 on ARM didn't have a good example for running ddev-webserver
Add example.
Rendered at https://20250416-amd64-touchup.ddev-com-front-end.pages.dev/blog/amd64-with-rosetta-on-macos/
=> AMD64 on ARM: Add better example for the run-webserver case

src/components/Header.astro, src/scripts/sponsors-banner.js
Adds Sponsor banner on ddev.com
Solves #339
=> feat: add sponsors banner to ddev.com, fixes #339

src/components/PostBody.astro, src/pages/404.astro, src/pages/blog/[id].astro
Open https://ddev.com/foobar
- "404" text is black, but it should be white for dark theme.
-  Giscus comments shouldn't be here.
- Uses white text for 404 in dark mode.
- Uses Giscus only for blog pages.
Open https://20250512-stasadev-giscus.ddev-com-front-end.pages.dev/foobar
Open blog page to make sure Giscus is still here https://20250512-stasadev-giscus.ddev-com-front-end.pages.dev/blog/ddev-may-2025-newsletter/
=> fix: use giscus only for blog pages, dark text color for 404

astro.config.mjs, package-lock.json, package.json
Updates npm packages and it's dependencies.
=> Bump Astro to 5.8.1 and Vite to 6.3.5 (for @astrojs/react)

src/components/BlogPostCard.astro, src/styles/global.css
Hover color is wrong here https://ddev.com/get-started/
And here https://ddev.com/blog/:
Sets white color on hover for dark mode:
And:
https://20250604-stasadev-hover-colo.ddev-com-front-end.pages.dev/get-started/
https://20250604-stasadev-hover-colo.ddev-com-front-end.pages.dev/blog/
=> fix: set white tab hover color, show blog date in dark mode

src/components/SponsorsBanner.astro
- #378
The logic was missing one `else` condition, where cached data should be updated.
- Refactors to several functions to make more readable.
- Uses non blocking async/await.
- Sets the cache for 12 hours.
https://20250610-stasadev-sponsorshi.ddev-com-front-end.pages.dev/
=> fix: update sponsorship cache, fixes #378

src/content/blog/ddev-docker-chromebook.md
The old Chromebook article is way out of date, and I got to try another one.
Rendered at https://20250704-chromebook-update.ddev-com-front-end.pages.dev/blog/ddev-docker-chromebook/
=> Update Chromebook blog about DDEV

public/_redirects, src/pages/blog/authors.astro
Not all redirects worked properly with/without trailing slashes.
- Groups redirects for better readability
- Adds proper redirects for `/ddev-local` and `/blog`
- Fixes black text on dark background in `/blog/authors`
All 4 links should be properly redirected:
- `https://20250721-stasadev-redirects.ddev-com-front-end.pages.dev/ddev-local/ddev-local-and-phpstorm-debugging-with-wsl2`
- `https://20250721-stasadev-redirects.ddev-com-front-end.pages.dev/ddev-local/ddev-local-and-phpstorm-debugging-with-wsl2/`
- `https://20250721-stasadev-redirects.ddev-com-front-end.pages.dev/blog/ddev-local-and-phpstorm-debugging-with-wsl2`
- `https://20250721-stasadev-redirects.ddev-com-front-end.pages.dev/blog/ddev-local-and-phpstorm-debugging-with-wsl2/`
Also:
- …
=> refactor: update redirect rules

public/_redirects, src/content/blog/ddev-add-on-maintenance-guide.md
The link is too long and may migrate somewhere else in the future.
Adds a short link.
Review https://20250804-stasadev-addon-upda.ddev-com-front-end.pages.dev/blog/ddev-add-on-maintenance-guide/
```
git clone https://github.com/ddev/ddev-redis
cd ddev-redis
curl -fsSL https://20250804-stasadev-addon-upda.ddev-com-front-end.pages.dev/s/addon-update-checker.sh | bash
```
=> feat: add short link for `addon-update-checker.sh`

src/components/quickstart/Windows.astro
- ddev/ddev#7524
Adds a big button for Windows Installer.
Click the button https://20250825-stasadev-download-w.ddev-com-front-end.pages.dev/get-started/
=> feat: add "Download Windows Installer" button, fixes ddev/ddev#7524

src/components/quickstart/Windows.astro
When installing DDEV, I got an error message saying that DDEV can't be installed. After [a discussion and troubleshooting on Discord](https://discord.com/channels/664580571770388500/1397288639503007825), re-installing the WSL with `wsl --install` and updating with `wsl --update` solved the problem. DDEV was installed smoothly.
Based on this, in some cases, running `wsl --update` command after installing WSL on Windows might be required to install DDEV successfully. 
This PR adds the command to the [Get Started](https://ddev.com/get-started/) page.
=> docs: add command to update wsl for Windows

src/content/blog/ddev-name-resolution-wildcards.md
Minor updates to https://ddev.com/blog/ddev-name-resolution-wildcards/
=> docs: Minor update to hostname resolution blog

src/content/blog/ddev-name-resolution-wildcards.md
We did a contributor training on the hostnames/DNS/ddev.site topic this week, but it mostly covers what's in the existing article, so updating the article with the video.
This is also the first test with a forked PR.
Here's the rendered URL. https://pr-431.ddev-com-fork-previews.pages.dev/blog/ddev-name-resolution-wildcards/
=> blog: Update the older hostname resolution blog with training video
